name: Teardown
on:
  workflow_dispatch: {}
permissions:
  contents: read
  id-token: write
jobs:
  teardown:
    runs-on: ubuntu-latest
    steps:
      - name: Setup python
        uses: actions/setup-python@v6
        with:
          python-version: 3.14
      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version: 24.14.0
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Install dependencies
        run: |
          npm install -g aws-cdk
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6.0.0
        with:
          aws-region: us-east-1
          role-to-assume: ${{ secrets.GHA_ROLE_ARN }}
      - name: Destroy stack
        env:
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
          AWS_REGION: ${{ env.AWS_REGION }}
        run: cdk destroy --app="python3 ${PWD}/app.py" --force