name: Teardown
on:
  workflow_dispatch: {}
permissions:
  contents: read
  id-token: write
jobs:
  teardown:
    runs-on: ubuntu-latest
    steps:
      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version: 24.14.0
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Install dependencies
        run: npm install -g aws-cdk
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6.0.0
        with:
          aws-region: us-east-1
          role-to-assume: ${{ secrets.GHA_ROLE_ARN }}
      - name: Destroy stack
        run: cdk destroy --app="python3 ${PWD}/app.py" --force